netobserv/network-observability-console-plugin

.gitignore
Dockerfile
README.md
console-extensions.json
http-server.sh
i18next-parser.config.js
locales/en/plugin__network-observability-plugin.json
package-lock.json
package.json
src/components/netflow-traffic.tsx
tsconfig.json
webpack.config.ts

Initial pull request for the plugin.
Create an Observe section with an empty Netflow traffic page.

NETOBSERV-51 : Bootstrap

---

OWNERS
package.json

Necessary for https://github.com/openshift/release/pull/23742

Add OWNERS, add test/lint script placeholders

---

Dockerfile
Makefile
README.md
console-extensions.json
locales/en/plugin__network-observability-plugin.json
package-lock.json
package.json
src/components/netflow-traffic.tsx

- Adding a makefile to have similar commands as in our other projects, including image building. Also there's a target to setup bridge.
- I changed the title from "Netflow traffic" to "Network Traffic" (more technology agnostic ; first words letter capitalized in titles, it's a common rule in openshift console)
- Switch to node 14, 12 being EOL soon
- Adding axios dependency for next tasks

Makefile, update readme, rename title

---

Makefile
README.md
pkg/handler/loki.go
pkg/handler/status.go
pkg/httpclient/http_client.go
pkg/model/loki.go
pkg/server/routes.go
pkg/server/server_test.go
web/src/api/loki.ts
web/src/api/routes.ts
web/src/components/netflow-traffic.tsx

This is temporary work to unlock next tasks on this console plugin
Many left TODOs are intentional and will be addressed via next tasks

Init fetching code for loki, dev mode only

---

web/console-extensions.json
web/locales/en/plugin__network-observability-plugin.json
web/package-lock.json
web/package.json
web/src/api/loki.ts
web/src/api/routes.ts
web/src/components/__tests-data__/columns.tsx
web/src/components/__tests-data__/flows.tsx
web/src/components/__tests__/netflow-table-header.spec.tsx
web/src/components/__tests__/netflow-table-row.spec.tsx
web/src/components/__tests__/netflow-table.spec.tsx
web/src/components/netflow-table-header.tsx
web/src/components/netflow-table-row.tsx
web/src/components/netflow-table.tsx
web/src/components/netflow-traffic.tsx
web/src/i18n.ts
web/webpack.config.ts

- Added patternfly dependency (had to configure css-loader and style-loader)
- Added netflow-table component
- Added netflow-table-header and netflow-table-row sub components
- Small bug correction preventing submenu display in kubernetes cluster
- Fixed locales generation in console-extensions

NETOBSERV-70: Create and display NetFlow table

---

web/enzyme.config.ts
web/package-lock.json
web/package.json
web/setup-tests.ts

Added enzyme setup for react 17
This allow usage of `mount` function

NETOBSERV-97 setup enzyme for react 17

---

web/src/components/__tests-data__/flows.tsx
web/src/components/__tests__/netflow-table-header.spec.tsx
web/src/components/__tests__/netflow-table.spec.tsx
web/src/components/netflow-table-row.tsx

Added tests for netflow-table sorting and found a small bug in netflow-table-raw keys.

NETOBSERV-105 Netflow table sort test

---

web/src/components/netflow-table-header.tsx
web/src/components/netflow-table-row.tsx
web/src/components/netflow-table.tsx
web/src/components/netflow-traffic.tsx
web/src/utils/__tests__/ip.spec.ts
web/src/utils/ip.ts

Numerical sorting was already done, at the end this task was more about adding address columns and their sorting.

NETOBSERV-79 Added ip addresses columns and special sorting for them

---

web/package-lock.json
web/package.json
web/src/components/netflow-table-row.tsx
web/src/components/netflow-table.tsx
web/src/utils/__tests__/port.spec.ts
web/src/utils/port.ts

Added a function to format the port column.

NETOBSERV-119 Added port number resolution to IANA service name

---

Dockerfile
Makefile
web/.eslintrc.js
web/.prettierrc.json
web/package-lock.json
web/package.json
web/src/api/loki.ts
web/src/api/routes.ts
web/src/components/__tests-data__/columns.tsx
web/src/components/__tests-data__/extensions.tsx
web/src/components/__tests-data__/flows.tsx
web/src/components/__tests__/columns-modal.spec.tsx
web/src/components/__tests__/netflow-table-header.spec.tsx
web/src/components/__tests__/netflow-table-row.spec.tsx
web/src/components/__tests__/netflow-table.spec.tsx
web/src/components/__tests__/netflow-traffic.spec.tsx
web/src/components/__tests__/refresh-dropdown.spec.tsx
web/src/components/columns-modal.tsx
web/src/components/netflow-table-header.tsx
web/src/components/netflow-table-row.tsx
web/src/components/netflow-table.tsx
web/src/components/netflow-traffic.tsx
web/src/components/refresh-dropdown.tsx
web/src/i18n.ts
web/src/utils/__tests__/ip.spec.ts
web/src/utils/__tests__/port.spec.ts
web/src/utils/duration.tsx
web/src/utils/ip.ts
web/src/utils/port.ts

- Add pretty-quick / prettier
- update dockerfile/makefile for frontend formatting invoked before building
- run formatting

Frontend formatting

---

web/src/components/__tests__/filters-toolbar.spec.tsx
web/src/components/filters-toolbar.css
web/src/components/filters-toolbar.tsx
web/src/components/netflow-traffic.tsx

- default time range fixed to 5 min
- protocol & port dropdown:
- manage `enter` key
- close dropdown on filter
- check empty value for all types
- clear all filters is now hidden when filters are empty

NETOBSERV-128 filters bugfix

---

Makefile

I forgot to update this command in the previous PR, breaking the make bridge command.

Fixing the make bridge command

---

Makefile
web/src/api/routes.ts

Related to: https://bugzilla.redhat.com/show_bug.cgi?id=2041605

Fixed modified plugin proxy url

---

pkg/loki/query.go

The comma also needs to be allowed.

Fix regexp to validate filter when multiple values are combined

---

web/package-lock.json
web/package.json

Add missing types for `CSSTransition` in `netflow-table-row.tsx`

Add missing types

---

web/webpack.config.ts

This PR temporary remove webpack externals config

NETOBSERV-210 fix console require error

---

OWNERS

Also remove QE/UX to avoid automatically asking them for reviewing

Add new approvers

---

web/setup-tests.ts
web/src/components/__tests__/netflow-traffic.spec.tsx
web/src/utils/__tests__/port.spec.ts
web/src/utils/config.ts

There is a warning about state modified outside of 'act' was triggered. Looks related to an enzyme issue: https://github.com/enzymejs/enzyme/issues/2073

Fix warning in test

---

web/src/components/query-summary/query-summary.tsx
web/src/components/query-summary/summary-panel.tsx

Fix summary reduce error when panel is kept open during refresh
https://issues.redhat.com/browse/NETOBSERV-273

NETOBSERV-273 Reducing empty array with no initial value

---

web/src/components/netflow-topology/element-panel.tsx
web/src/components/netflow-traffic.tsx

Fix missing metricFunction & metricType props on ElementPanel

NETOBSERV-240 merge fix

---

web/src/components/netflow-traffic.tsx

Removed topology feature gate.
I kept the `utils/features-gate.ts` file as example for next features

NETOBSERV-325 Topology: Remove feature gate

---

web/src/components/netflow-topology/netflow-topology.tsx

Automatically fit view when filters / options are updated

NETOBSERV-313 Topology: automatically fit view

---

web/src/api/ipfix.ts
web/src/components/__tests-data__/flows.ts
web/src/components/netflow-record/record-field.tsx
web/src/components/netflow-record/record-panel.tsx
web/src/components/netflow-table/__tests__/netflow-table.spec.tsx
web/src/utils/columns.ts
web/src/utils/duration.ts

/hold
requires https://github.com/netobserv/flowlogs-pipeline/pull/202 https://github.com/netobserv/network-observability-operator/pull/101 and

NETOBSERV-265 millisecond accuracy for time flow start/end

---

web/src/components/netflow-topology/netflow-topology.tsx

`updateModel` should not be called right after scope / group change. We need to wait for new metrics before update model.
This was creating wrong parent / child relationships since ids / content is reused on updates and scope was updated with old metrics.

NETOBSERV-364 Topology crash on scope change with groups

---

web/src/components/netflow-topology/element-panel.tsx
web/src/model/topology.ts

This PR fixes topology Nodes + Namespaces grouping and implements related metrics filters for the side panel.
Here is an example with Hosts + network-observability namespace:

NETOBSERV-581 - grouping for Nodes+NS broken

---

web/src/components/messages/loki-error.tsx

NETOBSERV-506 loki config url style

---

web/src/components/dropdowns/group-dropdown.tsx
web/src/components/netflow-topology/netflow-topology.tsx
web/src/components/netflow-traffic.tsx
web/src/model/topology.ts

Need to update the groups after scope is changed, not just from the options panel

Fix Too much recursion error

---

pkg/loki/topology_query.go
web/src/components/netflow-topology/element-panel.tsx

- Owner resource not well identified due to missing namespace aggregation
- In element panel, need to provide nodeType to get filter

Fix cases where filter button didn't work well

---

web/src/components/netflow-traffic-parent.tsx
web/src/components/netflow-traffic.tsx
web/src/utils/local-storage-hook.ts
web/src/utils/router.ts
web/src/utils/url.ts

This PR ensure top / limit is set correctly (especially at first time)
It also clear local storage if corrupted / on component crash to avoid any loop

NETOBSERV-650 Top X value is incorrect at first time

---

Dockerfile
Makefile

Layering npm install vs build to improve build time

Speed up docker build time

---

web/src/api/loki.ts
web/src/components/metrics/__tests__/metrics-content.spec.tsx
web/src/components/metrics/__tests__/stat-donut.spec.tsx
web/src/components/metrics/metrics-content.tsx
web/src/components/metrics/metrics-helper.tsx
web/src/components/metrics/metrics-total-content.tsx
web/src/components/metrics/stat-donut.tsx
web/src/components/netflow-overview/__tests__/netflow-overview-panel.spec.tsx
web/src/components/netflow-overview/netflow-overview.tsx
web/src/components/netflow-topology/element-panel.tsx

.. except in side-panel metrics, where less space is available

Follow-up on #239: do not truncate on tooltips..

---

web/src/components/netflow-traffic.tsx
web/src/utils/router.ts

Backport of https://github.com/netobserv/network-observability-console-plugin/pull/263

NETOBSERV-741 Backport

---

pkg/server/routes.go
pkg/server/server_test.go

https://github.com/netobserv/network-observability-console-plugin/pull/287

[1.1 backport] NETOBSERV-876 - api subrouter

---

web/src/components/metrics/metrics-content.tsx
web/src/components/metrics/stat-donut.tsx

Show metrics length in `data-test-metrics` attribute

Add length to metrics

---

pkg/utils/utils.go

backport of https://github.com/netobserv/network-observability-console-plugin/pull/340

NETOBSERV-1090: initialize empty slice for returning json [1.3 backport]

---

web/src/components/netflow-traffic.tsx
web/src/utils/filter-definitions.ts

It seems I had issues during rebase. This PR fix PktDrop & RTT flags checks.

NETOBSERV-1113 fix pktDrop & FlowRTT merge

---

web/package-lock.json
web/package.json

NETOBSERV-1445: update deps

---

.github/workflows/pull_request.yml
.github/workflows/push_image.yml
.github/workflows/push_image_pr.yml
.github/workflows/release.yml
.golangci.yml
Dockerfile
go.mod
pkg/server/server_test.go

NETOBSERV-1451: Bump ubi 9.3 / go 1.21

---

web/src/utils/__tests__/duration.spec.ts

Add unit tests on formatting durations
n/a

Add duration tests

---

web/src/components/dropdowns/topology-display-dropdown.css
web/src/components/metrics/histogram.tsx
web/src/components/metrics/metrics-content.css
web/src/components/metrics/metrics-donut.tsx
web/src/components/metrics/metrics-graph-total.tsx
web/src/components/metrics/metrics-graph.tsx
web/src/components/modals/export-modal.tsx
web/src/components/netflow-overview/netflow-overview.tsx
web/src/components/netflow-topology/element-panel-metrics.tsx
web/src/components/netflow-topology/element-panel.tsx
web/src/components/netflow-traffic.css
web/src/components/netflow-traffic.tsx
web/src/utils/export.ts

Backport of https://github.com/netobserv/network-observability-console-plugin/pull/463

NETOBSERV-1416 backport

---

web/src/components/modals/export-modal.tsx

Followup to fix columns conflict: Currently we can't update columns in table anymore.
n/a

NETOBSERV-1416 Various console plugin issues followup

---

web/src/components/modals/export-modal.tsx

Backport of https://github.com/netobserv/network-observability-console-plugin/pull/466

NETOBSERV-1416 followup backport

---

web/src/components/netflow-topology/netflow-topology.tsx
web/src/components/scope-slider/scope-slider.css
web/src/components/scope-slider/scope-slider.tsx

Backport of https://github.com/netobserv/network-observability-console-plugin/pull/468

NETOBSERV-1475 Backport

---

web/src/components/netflow-overview/netflow-overview.css
web/src/components/netflow-overview/netflow-overview.tsx

Fix wrong sizing on single focus graph mode
n/a

NETOBSERV-1485 Single focus sizing issue

---

web/src/components/netflow-overview/netflow-overview.css
web/src/components/netflow-overview/netflow-overview.tsx

Backport of https://github.com/netobserv/network-observability-console-plugin/pull/470

NETOBSERV-1485 Backport

---

web/src/api/ipfix.ts
web/src/components/netflow-record/record-panel.tsx

Backport of https://github.com/netobserv/network-observability-console-plugin/pull/475

NETOBSERV-1496 Backport

---

Makefile

Fix serve target not taking config properly
n/a

fix serve target

---

web/cypress/support/const.ts

fix cypress: added 1 column

---

scripts/cypress.sh

disable color codes for cypress tests 
n/a

disable color codes

---

pkg/loki/flow_query.go
pkg/model/filters/logql.go

https://github.com/netobserv/network-observability-console-plugin/pull/533

Backport of NETOBSERV-1630

---

web/cypress/e2e/table/table.spec.ts
web/src/components/netflow-traffic.tsx
web/src/utils/url.ts

Fix different scenarios where URL parameters are not correctly initialized / updated.
n/a

NETOBSERV-1733 fix url filters init / update

---

.tekton/network-observability-console-plugin-pull-request.yaml
.tekton/network-observability-console-plugin-push.yaml

Removed base image ref in konflux

---

web/src/components/modals/__tests__/overview-panels-modal.spec.tsx
web/src/components/modals/modals.tsx
web/src/components/modals/overview-panels-modal.tsx

Fix Overview panels filters not working properly.
These will now adapt according to enabled features.
n/a

NETOBSERV-1540 fix panels filter chips

---

.github/workflows/push_image.yml

Add standalone build to github action CI on push

automate standalone build

---

web/src/model/__tests__/export-query.spec.ts
web/src/model/export-query.ts

Do not stringify undefined fields as they end up == "undefined"
n/a

NETOBSERV-1958: fix CSV export

---

.tekton/pipeline-ref.yaml

Fixing source image tagging in konflux
n/a

Fixing source image tagging in konflux

---

.tekton/pipeline-ref.yaml

Adding rmps scan task to konflux
n/a

Adding rmps scan task to konflux

---

.tekton/pipeline-ref.yaml
Dockerfile.downstream

Fixing build version during image build
n/a

Fixing build version during image build

---

.tekton/pipeline-ref.yaml

Konflux deprecated results

---

web/src/components/drawer/record/record-field.css
web/src/components/drawer/record/record-field.tsx

Backport of https://github.com/netobserv/network-observability-console-plugin/pull/700

[Backport] NETOBSERV-2049: Console table rows height are inconsistent

---

.tekton/network-observability-console-plugin-1-8-pull-request.yaml
.tekton/network-observability-console-plugin-1-8-push.yaml

Release-1.8 : Reenabling ppc64le build

---

Dockerfile.downstream

Fixing konflux security violations

---

web/src/components/drawer/record/record-field.css

Text ellipsis: display as much as possible
n/a

NETOBSERV-2119: use word-break break-all

---

web/console-extensions.json

Backport of https://github.com/netobserv/network-observability-console-plugin/pull/754

NETOBSERV-2139 backport

---

web/src/utils/columns.ts

@jpinsonneau quick fix here on sorting ipsec columns

Fix ipsec column considered as IP

---

.github/workflows/release.yml

This aligns with FLP and agent where we automatically create the draft

Create draft release automatically

---

web/src/components/forms/dynamic-form/widgets.tsx
web/src/components/forms/editor-toggle.tsx
web/src/components/forms/flowCollector-status.tsx
web/src/components/forms/resource-form.tsx

Add missing ids for tests
