Makefile, README.md
- fix GOFLAGS issue
- Separate frontend and backend make targets to be able to separate as
well in CI
- Helper tags "make frontend" and "make backend" for build+lint+test
=> Update make for CI

cmd/plugin-backend.go, pkg/handler/loki.go, pkg/httpclient/http_client.go, pkg/server/routes.go, pkg/server/server.go, pkg/server/server_test.go
For multi-tenant Loki setups, this PR allows specifying the `loki-tenant-id` CLI argument, which will forward this value to loki as the `X-Scope-OrgID` header.
More details of this header: https://grafana.com/docs/loki/latest/operations/multi-tenancy/
=> NETOBSERV-98: specify loki tenant id

web/locales/en/plugin__network-observability-plugin.json, web/src/components/__tests-data__/columns.tsx, web/src/components/__tests__/columns-modal.spec.tsx, web/src/components/__tests__/netflow-traffic.spec.tsx, web/src/components/columns-modal.css, web/src/components/columns-modal.tsx, web/src/components/netflow-table-header.tsx, web/src/components/netflow-traffic.tsx
Added toolbar with manage columns icon button. This toolbar will be used for filters also
- Popup allow you to select / reorder columns
- Refresh is done on save
- You can select / unselect all
- Reset action restore default order / selection
- At least one column must be selected
| ![image](https://user-images.githubusercontent.com/91894519/145969871-273c772a-a3cb-4d07-bb60-f6025651e386.png)|![image](https://user-images.githubusercontent.com/91894519/145970078-ce6fd40b-a0e6-4007-b395-51b0ba39bb50.png)|![image](https://user-images.githubusercontent.com/91894519/145970014-13c896d5-f5a7-4324-80d2-99997518ac75.png)|
| ------------- | ------------- |------------- |
=> NETOBSERV-71 added toolbar with select column modal

web/src/components/netflow-table.tsx, web/src/utils/__tests__/port.spec.ts, web/src/utils/port.ts
Modifications based on Steven review:
https://github.com/netobserv/network-observability-console-plugin/pull/25#discussion_r773316416
=> NETOBSERV-119 Changed port sort behavior to have numerical port last

web/package.json, web/src/components/filters-toolbar.tsx, web/src/utils/columns.ts, web/src/utils/router.ts
This PR remove lint issues :
- Allow inline config
- Added some types for filters
The comments like `/* eslint-disable @typescript-eslint/no-explicit-any */` were crashing on `fix-imports` script. 
They are now ignored at this step.
=> Fix Lint Warning

web/src/components/__tests__/filters-toolbar.spec.tsx, web/src/components/__tests__/netflow-table.spec.tsx, web/src/components/filters-toolbar.tsx, web/src/components/netflow-table.tsx, web/src/components/netflow-traffic.tsx
When filters are added/deleted/cleared, it should show the spinning icon in the table.
This PR also enables the "clear all filters" button in the "no results found" message:
=> NETOBSERV-117: show spinning icon when filters are added/deleted

Dockerfile, Makefile
Dockerfile now use npm ci to prevent lock file modifications.
=> Dockerfile now use npm ci to prevent lock file modifications

web/src/components/__tests__/netflow-table.spec.tsx, web/src/components/netflow-table.tsx, web/src/components/netflow-traffic.tsx, web/src/utils/columns.ts
Fix sort when `setFlows` is called
- Sort result is kept locally in table component to avoid render of other components that don't take order in count
- uses `getFlowValueFromColumnId` to simplify code
=> Fix sort on refresh

web/setup-tests.ts, web/src/components/__tests__/netflow-traffic.spec.tsx, web/src/components/netflow-traffic.tsx, web/src/utils/local-storage-hook.ts
Save columns, refresh and size to localStorage
You can specify `opts` in `useLocalStorage` hook to save only ids of array on desired criteria.
=> NETOBSERV-125 localStorage hook

web/src/components/netflow-table/netflow-table-row.css
Add table row stripping using `pf-color-black-150`
I can't see it when my screen is in comfort mode (low luminosity) but it's clearly visible using normal contrast / luminosity. We can move to `pf-color-black-100` if you feel it's too dark.
=> NETOBSERV-120 table row stripping

pkg/server/server_test.go
The removed test is equivalent to the previous line (just removing the namespace), but adding two arguments might lead to flaky tests due to the unconsistent sorting of map elements.
=> Fix loki filtering server flaky test

pkg/server/server_test.go
This is fixing a flaky test when starting servers for tests.
It doesn't fail on CI, but it can fail in different environments. The problem was that, while starting the server, it was expecting to find frontend assets in `./web/dist` ; which is indeed the case when you build the frontend before the backend, or when you haven't cleaned up a previous build.
But it was failing for me because I had cleaned up that directory and was running only backend build/test.
The suggestion to fix that here, is to not rely on actual frontend assets, but create dummy assets instead in a temporary directory, and start the server from there.
=> Fix flaky test starting servers

web/src/api/routes.ts
Changed route between frontend and backend since the backend now use proxy alias to be namespace agnostic.
=> NETOBSERV-116: Fix namespace deployment

pkg/handler/loki.go
Remove array indicator from params keys that broke labels / ips filtering
This is related to changes around `type QueryArguments = { [k in AnyQueryArgs]?: unknown };` that now sends array of values instead of a comma separated string so the backend receive array indicators in keys that contains multiple values.
That could be useful in the future for more complex cases and to simplify switch / case on backend side
=> Fix filters params

web/src/components/netflow-traffic.tsx, web/src/utils/__tests__/errors.spec.ts, web/src/utils/errors.ts
E.g. with "not found" as plain text:
=> Fix displaying some errors (e.g. plain text response)

pkg/handler/loki.go, pkg/handler/loki_test.go, pkg/server/server_test.go, web/src/utils/router.ts
JIRA https://issues.redhat.com/browse/NETOBSERV-159
This is fixing a couple of things, in addition to the mentioned JIRA.
- back to using multiple values in query param as a single
coma-separated string, because the other params were ignored in go on
parsing
- fix removing an extra "|" when several values per key are used (now
use '|' instead of '||', which was a bug)
- fixed a case where empty regex was written
- rewrite regexp, hopefully easier to read, and dissociate the numeric
case versus text case
- Add some unit tests on LogQL building
=> NETOBSERV-159 fix several issues in LoQL builder

web/console-extensions.json
Following QE feedbacks, it appear there is regression in console side on latests nightly 4.10 builds
The deployment tab makes the console crash so this PR remove our tab from the `console-extensions.json` file until a fix is done on `console` side
Ensure your browser cache is cleared to apply this change.
=> NETOBSERV-121 removed deployment tab

pkg/handler/loki.go, pkg/handler/loki_test.go, pkg/server/server_test.go
I first tried to address this issue escaping special characters, but there are many different special characters and many different case to handle making this approach quit complex.
According to [grafana doc ](https://grafana.com/docs/loki/latest/logql/log_queries/), backtick can be used to avoid escaping all other characters. Then I disallowed backtick from flows requests to prevent injection using backticks.
=> NETOBSERV-133: Fix logql injection from filters

README.md, web/console-extensions.json, web/webpack.config.ts
Modules concatenation in production mode was crashing console application before calling plugin code
Different versions of dependencies between console and plugins are the root cause of this issue
Disabling `concatenateModules` option solve versions issues by keeping dependencies separated between the two projects
=> NETOBSERV-121 restore deployment tab

web/src/components/filters-toolbar.tsx
Adding new filter criteria moves the filter controls to the right:
This PR keeps the controls aligned to the left:
=> Align table filter controls

web/src/components/netflow-table/__tests__/netflow-table-header.spec.tsx, web/src/components/netflow-table/netflow-table-header.tsx, web/src/components/netflow-table/netflow-table.tsx, web/src/components/netflow-traffic.css, web/src/utils/columns.ts
With this change, the columns width are fixed, hence they can exceed the width of the page container (resulting in showing horizontal scroll). The goal is to avoid showing too small cells that are barely not visible, like here:
Now, with fixed width:
@jpinsonneau @OlivierCazade @mariomac could you test it and give feedback if it works well for you , given your screen resolution? The idea is that the default columns should work for most resolutions.
Let me know also if you think this isn't the right approach (but in any case I'd like to fix the issue I was having with too small columns)
=> Fixed width columns

pkg/handler/loki.go
Looks like and symbol still create some parsing error with loki parsing even if they are escaped using backquote.
Disabling them since they are not used anyway in pod or namespace name.
This is an addition to this PR:
https://github.com/netobserv/network-observability-console-plugin/pull/57
=> Disabling and sign in flows request

cmd/plugin-backend.go, pkg/handler/loki.go, pkg/loki/query.go, pkg/loki/query_test.go, pkg/server/server_test.go, pkg/utils/utils.go
This PR is part of [NETOBSERV-169](https://issues.redhat.com/browse/NETOBSERV-169) - Create index on FlowDirection
Changes:
- Get Loki labels from flag to allow operator to set them on both `goflow kube` and `console plugin backend`
Check https://github.com/netobserv/network-observability-operator/pull/54
=> NETOBSERV-169 labels from flag

pkg/loki/query.go, web/src/api/ipfix.ts, web/src/components/__tests-data__/flows.ts, web/src/utils/columns.ts
It fixes data displayed in Direction column or in the details panel: without it, all flows were always displayed as EGRESS
=> FlowDirection must be read from labels now

web/src/utils/__tests__/port.spec.ts, web/src/utils/filters.ts, web/src/utils/port.ts
IANA ports reservation is mostly respected for ports below 1024, this PR limit port to `service`translation to this ports.
[Corresponding JIRA ticket](https://issues.redhat.com/browse/NETOBSERV-187)
=> NETOBSERV-187 : Restrict port to service formatting to ports below 1024

pkg/loki/query.go, pkg/server/server_test.go, web/locales/en/plugin__network-observability-plugin.json, web/src/components/filters-toolbar.tsx
Following @memodi comment on [NETOBSERV-176](https://issues.redhat.com/browse/NETOBSERV-176) we can add case insensitive to regex when text is not quoted
I have added an example in the "Learn more" section.
It seems there is no performance changes for this implementation,  at least for our queries
=> NETOBSERV-176 regex case insensitive

.github/workflows/release.yml
Similar to the existing push-to-quay action, except it's triggered from
tags and will push just 1 image built using that tag as version.
https://issues.redhat.com/browse/NETOBSERV-192
=> NETOBSERV-192 Release action

pkg/handler/csv/loki_csv.go, pkg/handler/loki.go, pkg/handler/response.go, pkg/loki/query.go, web/src/utils/columns.ts
https://issues.redhat.com/browse/NETOBSERV-227
- filters on "SrcK8S_OwnerName" or "DstK8S_OwnerName" shouldn't trigger
common filters processing
- "Namespace" was renamed "K8S_Namespace"
- Use more generic solution to retrieve CommonLabelFilter out of
configured labels
- side change: move CSV related functions to a different package to
improve readability
=> NETOBSERV-227 fix filtering by namespace or owner

Makefile
Yesterday I accidentally pushed the "main" image on quay (I rollbacked minutes later).
This change should avoid such a situation
=> Use default TAG=dev to prevent accidental push on main by quay admins

.github/workflows/push_image.yml, .github/workflows/push_image_pr.yml, .github/workflows/rm-ok-to-test.yaml, Makefile, shortlived.Dockerfile
https://issues.redhat.com/browse/NETOBSERV-229
New github action workflow to build and push images per pull request.
Some security consideration: pushing images requires QUAY_SECRET to be used, which isn't
available in the 'pull_request' trigger, so we have to use
'pull_request_target' instead. This trigger uses the base branch HEAD,
rather than the PR's HEAD to execute the workflow, to prevent attacks
stealing secrets. Still, it could be vulnerable to attacks stealing secret from the build itself. So as an additional measure, we inculde a user validation check, so that only allowed users (maintainers) have their PR image built.
=> NETOBSERV-229 CI: create pre-merge images

pkg/loki/flow_query.go, pkg/server/server_flows_test.go
doing a "trick" by matching for a coma after the port value, to ensure exact match. It works as long as port isn't the last field (which is never the case afaik). The other option could be to do an explicit exact match after a json extraction, which is probably cleaner but less performant. So, it's debatable...
=> NETOBSERV-269 Port exact match

pkg/handler/loki.go, pkg/loki/matrix_merger.go, pkg/loki/matrix_merger_test.go, pkg/loki/streams_merger.go, pkg/loki/streams_merger_test.go
Following https://github.com/netobserv/network-observability-console-plugin/pull/105 Matrix merger was not implemented
This adds the missing backend part to run topology queries keeping the `fetchParallel` approach.
I have some concerns about performances since we are replacing Loki `Query Frontend` role by splitting queries on our side. This can generate thousands internal queries.
https://grafana.com/docs/loki/latest/configuration/query-frontend/#parallelization
We can unlock the situation with this PR and decide what to do next after performance testing.
=> NETOBSERV-226 matrix merger implementation

pkg/loki/flow_query.go, pkg/server/server_flows_test.go
Fixes https://github.com/netobserv/network-observability-console-plugin/pull/105#issuecomment-1092730150
wrong "dns-default" appearing when searching for dest name loki
=> Fix linefilter regex, disallowing '"' in before-match

web/src/components/netflow-topology/components/edge.tsx, web/src/components/netflow-topology/components/node.tsx, web/src/components/netflow-topology/netflow-topology.css, web/src/components/netflow-topology/netflow-topology.tsx, web/src/components/netflow-topology/styles/styleEdge.tsx, web/src/components/netflow-topology/styles/styleNode.tsx, web/src/model/topology.ts
View updates on hover / select events:
- highlight related node / edges in blue
- Bring the content to front (node / edge)
- show quick actions on hover
`DefaultNode` & `DefaultEdge` components from PF library are now included in our code to be able to manage layers and hover events
=> NETOBSERV-254 Topology highlight on hover

web/src/components/netflow-record/record-field.css, web/src/components/netflow-table/__tests__/netflow-table-row.spec.tsx, web/src/components/netflow-table/netflow-table-header.tsx, web/src/components/netflow-table/netflow-table-row.tsx, web/src/components/netflow-table/netflow-table.css, web/src/components/netflow-table/netflow-table.tsx, web/src/components/netflow-traffic.css
This PR is related to https://github.com/netobserv/network-observability-console-plugin/pull/121 about performances with a high limit. 
It removes row items outside of visible area of table scroll. 
These items are replaced by empty divs so the scroll behavior stay normal. 
This approach decrease 19x the total rendering time on 1k rows.
The rendering may differ between browsers:
- chrome seems to render after items added / removed
- firefox first render empty rows and directly add them
As discussed, we can merge both https://github.com/netobserv/network-observability-console-plugin/pull/121 & this PR to be able to show a lot of items per page.
=> NETOBSERV-288 - conditionnal rendering to improve perfs on table

pkg/handler/flows.go, pkg/handler/loki.go, pkg/handler/resources.go, pkg/handler/resources_test.go, pkg/handler/topology.go, pkg/httpclient/http_client.go, pkg/httpclient/httpclienttest/http_client_mock.go, pkg/server/routes.go, web/src/api/routes.ts, web/src/model/__tests__/resource.spec.ts, web/src/model/resource.ts, web/src/utils/__tests__/label.spec.ts, web/src/utils/label.ts
- Fix Resource filters when kind is Node (missing API endpoint, bugged
split function)
- Fix allowing '.' in kubernetes names (for nodes)
- Add tests on both sides back/front; on the backend, create an
httpClientMock that can easily be reused for mocking loki
=> NETOBSERV-279 fix issues with filters on nodes

web/src/components/query-summary/summary-panel.tsx
Linked to `formatPort` & `formatProtocol` from utils
=> NETOBSERV-272 - NETOBSERV-274 - Query protocols & stats, port names

web/src/components/netflow-record/record-panel.tsx, web/src/components/netflow-topology/element-panel.tsx, web/src/components/netflow-topology/options-panel.tsx, web/src/components/netflow-traffic.css, web/src/components/netflow-traffic.tsx, web/src/components/query-summary/summary-panel.tsx, web/src/utils/panel.tsx
This PR is part of UI feedback / followup. It implements resizable panel and improve UX on selections / view switch. The selections will now close on view change.
=> NETOBSERV-270 resizable panel

web/src/utils/columns.ts
Fix crash on common columns sorting
These columns contains array values that needed to be converted before sort
=> NETOBSERV-322 Sort crash on common columns

web/src/components/query-summary/summary-panel.tsx
Fix query summary port sort crashing when `formatPort` was done before `comparePorts`
=> NETOBSERV-321 query stats panels crashes netflow-traffic page

web/src/components/netflow-topology/__tests__/netflow-topology.spec.tsx, web/src/components/netflow-topology/netflow-topology.tsx, web/src/components/netflow-traffic.tsx, web/src/model/topology.ts
This is a workaround for topology view crashing on group expand after model change. The model is now reloaded all the time and `collapsed` param updated from previous value between refresh.
=> NETOBSERV-293 Topology: Expand groups crash after refresh

pkg/handler/csv/loki_csv.go, pkg/handler/flows.go, pkg/handler/loki.go, pkg/handler/response.go, pkg/handler/topology.go, pkg/loki/matrix_merger.go, pkg/loki/matrix_merger_test.go, pkg/loki/merger.go, pkg/loki/streams_merger.go, pkg/loki/streams_merger_test.go, pkg/model/loki.go, pkg/model/loki_test.go, pkg/server/server_test.go, web/locales/en/plugin__network-observability-plugin.json, web/src/api/loki.ts, web/src/api/routes.ts, web/src/components/__tests-data__/flows.ts, web/src/components/__tests__/netflow-traffic.spec.tsx, web/src/components/dropdowns/__tests__/query-options-dropdown.spec.tsx, web/src/components/dropdowns/query-options-dropdown.tsx, web/src/components/netflow-traffic.tsx, web/src/components/query-summary/__tests__/query-summary.spec.tsx, web/src/components/query-summary/__tests__/summary-panel.spec.tsx, web/src/components/query-summary/query-summary.tsx, web/src/components/query-summary/summary-panel.tsx
- Stats are now aggregated in backend (needed when multiple queries are performed)
- Add a few tests
- On the frontend, limit reached now comes as a stats provided from
backend
- Add info tooltip on limit setting, to clarify it's the limit per loki
query, so we may end up with more flows than this limit
=> NETOBSERV-287 Aggregate stats, fix limit reach

cmd/plugin-backend.go, pkg/handler/loki.go, pkg/httpclient/http_client.go, pkg/loki/config.go, pkg/loki/query_test.go, pkg/server/server_flows_test.go
Skip TLS checks until https://issues.redhat.com/browse/NETOBSERV-309 implementation
This will be usefull for https://github.com/netobserv/network-observability-operator/pull/59 since Loki Operator uses its own certificates
=> NETOBSERV-219 PoC Operators - skip TLS checks

web/src/components/modals/export-modal.tsx, web/src/components/netflow-table/__tests__/netflow-table-header.spec.tsx, web/src/components/netflow-table/__tests__/netflow-table.spec.tsx, web/src/components/netflow-table/netflow-table-header.tsx, web/src/components/netflow-table/netflow-table.tsx, web/src/components/netflow-traffic.tsx, web/src/utils/local-storage-hook.ts, web/src/utils/url.ts
Either wait for https://github.com/netobserv/network-observability-console-plugin/pull/148 or close it (already included here).
Also https://github.com/netobserv/network-observability-console-plugin/pull/131 will be impacted since topology display has been merged into options.
This PR adds missing parameters to local storage and restore them when page is loaded.
```
{
"netflow-traffic-query-params": "filters=resource%3DPod.openshift-operator-lifecycle-manager.olm-operator-55d596d44-qhlxn&timeRange=300&limit=100&match=all&reporter=destination&function=sum&type=bytes",
"netflow-traffic-sort-id": "EndTime",
"netflow-traffic-sort-direction": "asc",
"netflow-traffic-columns": [
"EndTime",
"SrcK8S_Type",
"SrcPort"
],
"netflow-traffic-size-size": "m",
"netflow-traffic-view-id": "topology"
}
``` …
=> NETOBSERV-290 Preserve settings in NetFlow table

web/src/components/modals/__tests__/time-range-modal.spec.tsx, web/src/components/modals/time-range-modal.tsx
This PR add seconds to time pickers in custom time range modal
Seconds are not mandatory and will be set to 00 if not specified (as same as minutes)
It also fix a refresh issue while typing from keyboard
=> NETOBSERV-298 Custom time range forgets the seconds

pkg/loki/topology_query.go, pkg/model/fields/fields.go, pkg/server/server_test.go, web/locales/en/plugin__network-observability-plugin.json, web/src/api/ipfix.ts, web/src/api/loki.ts, web/src/components/filters/__tests__/text-filter.spec.tsx, web/src/components/netflow-record/record-field.tsx, web/src/components/netflow-record/record-panel.tsx, web/src/components/netflow-topology/element-panel.tsx, web/src/components/netflow-topology/netflow-topology.tsx, web/src/model/filters.ts, web/src/model/topology.ts, web/src/utils/columns.ts, web/src/utils/filter-definitions.ts
You will up to date [flowlogs-pipeline](https://github.com/netobserv/flowlogs-pipeline) to get `K8S_HostName` fields.
This PR adds `Node Name`:
- Columns
- Filters
- Replaced Node IP by names in topology
Also removed empty / duplicated fields on side panel when a `Node` is selected
=> NETOBSERV-253 Topology: Enrich Host informations

web/src/components/netflow-topology/__tests__/element-panel.spec.tsx, web/src/components/netflow-topology/element-panel.tsx, web/src/components/netflow-topology/netflow-topology.tsx, web/src/components/netflow-traffic.tsx, web/src/model/topology.ts
This PR implements filtering from side panel on both topology nodes & edges.
Filtering from `netflow-topology` has been merged into a single place so we will need to wait for https://github.com/netobserv/network-observability-console-plugin/pull/131 & https://github.com/netobserv/network-observability-console-plugin/pull/146
=> NETOBSERV-259 Topology: Filter from side panel

web/src/components/__tests__/netflow-traffic.spec.tsx, web/src/components/netflow-traffic.tsx, web/src/utils/poll-hook.ts
This PR fix `tick` race issue found by @memodi. 
It seems that `jest` behavior has changed but I'm open to any suggestion
=> NETOBSERV-290 fix tick race issues

web/src/components/netflow-topology/components/node.tsx, web/src/components/netflow-topology/netflow-topology.tsx, web/src/components/netflow-topology/styles/styleNode.tsx, web/src/model/topology.ts
This PR fix `Popovers` hiding too fast on topology:
- fixed hover state
- added and event to hide opened popover on pan / zoom
- fixed edges with same source / destination making hover blinking in some situations
You can now select `text` / click on `ResourceLink` in the Popover
=> NETOBSERV-344 Can't click on node info from popup

web/src/utils/router.ts
Currently we can have both `TimeRange` / `StartTime` and `EndTime` parameters in the url. This should not be allowed.
=> NETOBSERV-361 Fix time range url issue

web/src/components/netflow-topology/element-panel.tsx, web/src/model/topology.ts
Fix bidirectionnal edges in topology view
This was broken since refresh model changes in https://issues.redhat.com/browse/NETOBSERV-293
=> NETOBSERV-363 Bidirectional edges doesn't work anymore

web/src/components/netflow-record/__tests__/record-field.spec.tsx, web/src/components/netflow-record/record-field.css, web/src/components/netflow-record/record-field.tsx, web/src/components/netflow-table/netflow-table.css, web/src/components/netflow-table/netflow-table.tsx
`getRowHeight` function has been updated to rely only on `rem`.
All `px` mentions has been removed from the css files.
Size is now dynamic according to selected columns. If you select at least one common column, the size will be increased to allow additionnal row(s).
I found some issues when datetime were too long especially when side menu is open so I forced them to be singleline on small size.
=> NETOBSERV-317 Netflow table: reduce row height / do not compute in px

web/src/components/dropdowns/display-dropdown.tsx, web/src/components/dropdowns/group-dropdown.tsx, web/src/components/dropdowns/layout-dropdown.tsx, web/src/components/dropdowns/metric-function-dropdown.tsx, web/src/components/dropdowns/metric-type-dropdown.tsx, web/src/components/dropdowns/query-options-dropdown.tsx, web/src/components/dropdowns/refresh-dropdown.tsx, web/src/components/dropdowns/scope-dropdown.tsx, web/src/components/dropdowns/time-range-dropdown.tsx, web/src/components/dropdowns/truncate-dropdown.tsx, web/src/components/filters/autocomplete-filter.tsx, web/src/components/filters/filter-hints.tsx, web/src/components/filters/filters-dropdown.tsx, web/src/components/filters/filters-toolbar.tsx, web/src/components/modals/columns-modal.tsx, web/src/components/modals/export-modal.tsx, web/src/components/modals/modal.tsx, web/src/components/modals/time-range-modal.tsx, web/src/components/netflow-record/record-field.tsx, web/src/components/netflow-record/record-panel.tsx, web/src/components/netflow-table/netflow-table-header.tsx, web/src/components/netflow-table/netflow-table-row.tsx, web/src/components/netflow-table/netflow-table.tsx, web/src/components/netflow-topology/components/edge.tsx, web/src/components/netflow-topology/element-panel.tsx, web/src/components/netflow-topology/netflow-topology.tsx, web/src/components/netflow-topology/options-panel.tsx, web/src/components/netflow-traffic-parent.tsx, web/src/components/netflow-traffic.tsx, web/src/components/query-summary/summary-panel.tsx
I have added a lot of missing `data-test` on butons / dropdowns. 
We can remove `id` field in these cases and update jest tests if you prefer or keep them as is.
Also added `data-test` /  ~~`data-test-id`~~ on table components including rows & fields and on side panel
For topology you can already rely on data-XXX content like:
```
<g data-id="Namespace.undefined.openshift-network-diagnostics.undefined.undefined" data-kind="node" data-type="node" 
```
=> NETOBSERV-326 data-test attributes

web/moduleMapper/dummy.tsx, web/src/components/netflow-table/__tests__/netflow-table-row.spec.tsx, web/src/components/netflow-table/netflow-table-row.css, web/src/components/netflow-table/netflow-table-row.tsx, web/src/components/netflow-table/netflow-table.tsx, web/src/utils/k8s-models-hook.ts
Following https://github.com/netobserv/network-observability-console-plugin/pull/169 some performances issues occurs depending on your resolution / window size changes. Browser freeze and a prompt ask to exit page in worst cases.
This PR change the way rows are skipped keeping PF table `Tr` with their attributes and only remove their content.
Also, `CSSTransition` has been moved on `Tr` level to avoid repeating these on each `Td`
=> NETOBSERV-317 fix rendering performances issue

web/src/components/filters/__tests__/filters-toolbar.spec.tsx, web/src/components/filters/filters-toolbar.css, web/src/components/filters/filters-toolbar.tsx, web/src/components/netflow-traffic.tsx, web/src/model/filters.ts, web/src/utils/local-storage-hook.ts, web/src/utils/router.ts
This brings ability to click on group / value filter text to enable / disable it without loosing the values.
State is saved in `localStorage` so the url params are kept as before.
We decided to follow PF colors for now but feel free to suggest alternatives in related [slack conversation](https://coreos.slack.com/archives/C02939DP5L5/p1654855230111639)
=> NETOBSERV-347 UX filtering: be able to turn off an active filter

web/package-lock.json, web/package.json, web/src/components/netflow-table/netflow-table-row.tsx, web/src/components/netflow-table/netflow-table.tsx
This PR fixes the following issues that happens on query changes after scrolling:
It adds `data-last-render` attribute containing a `timestamp` on every `tr` and remove previous ones (if any) every time flows are updated.
This seems to be a bug in PF `TableComposable` that sometimes keeps previous rows when multiple refresh occurs on the same table instance.
I have also took the opportunity to update dependencies :smiley_cat:
=> NETOBSERV-399 Table rows display issue after update

web/locales/en/plugin__network-observability-plugin.json, web/src/components/netflow-traffic.tsx, web/src/components/query-summary/__tests__/query-summary.spec.tsx, web/src/components/query-summary/__tests__/summary-panel.spec.tsx, web/src/components/query-summary/query-summary.tsx, web/src/components/query-summary/summary-panel.tsx
I added the last refresh date in the query summary component instead of below the refresh button because adding it below the refresh button would have broke consistency with other console pages that use this refresh button and don't show the last refresh date.
=> NETOBSERV-299 : Added last refresh date in query summary

cmd/plugin-backend.go, pkg/handler/loki.go, pkg/loki/config.go, pkg/loki/query_test.go, pkg/server/server_flows_test.go, pkg/server/server_test.go
This PR adds Authorization header to loki client from specified `loki-token-path`
=> NETOBSERV-101 R&D: Kube enricher write path for downstream operator

Dockerfile
This facilitate downstream build since we don't need to manually update npm anymore.
I tested the built image and did not see any difference.
=> Updated Dockerfile to use node 16

web/src/utils/protocol.ts
This ensure `formatProtocol` to get existing protocol name without crashing.
Else it returns 'N/A'
=> NETOBSERV-546 formatProtocol crash on unknown protocol number

web/src/model/topology.ts, web/src/utils/ids.ts
This PR put topology ids generation in a separate file to allow QE to easy reuse these.
It also remove all the `.undefined.` parts in these and document the possibilities
=> NETOBSERV-554 - Topology test ids generation

web/src/model/topology.ts, web/src/utils/ids.ts
https://github.com/netobserv/network-observability-console-plugin/pull/193 introduced a bug in multy grouping because of the id generation.
This PR restore parent id in groups that fixes this issue
=> NETOBSERV-581 & NETOBSERV-554 fix group id

pkg/handler/csv/loki_csv.go, web/src/components/netflow-traffic.tsx
This PR force `TimeFlowStartMs`,  `TimeFlowEndMs` & `TimeReceived` to be exported  as firsts columns in the csv file.
These are not listed anymore on front end side in the export popup.
It also fixes a bug on labels.
=> NETOBSERV-487 - deselecting "Export all datas" causes few columns to be missed

cmd/plugin-backend.go, pkg/loki/topology_query.go, web/locales/en/plugin__netobserv-plugin.json, web/src/components/metrics/metrics-content.tsx, web/src/components/netflow-overview/__tests__/netflow-overview-panel.spec.tsx, web/src/components/netflow-overview/__tests__/netflow-overview.spec.tsx, web/src/components/netflow-overview/netflow-overview-panel.tsx, web/src/components/netflow-overview/netflow-overview.tsx, web/src/components/netflow-traffic.tsx, web/src/components/query-summary/__tests__/query-summary.spec.tsx, web/src/components/query-summary/__tests__/summary-panel.spec.tsx, web/src/components/query-summary/query-summary.tsx, web/src/components/query-summary/summary-panel.tsx, web/src/model/flow-query.ts
This PR replaces previous https://github.com/netobserv/network-observability-console-plugin/pull/194 after computed metrics fix https://github.com/netobserv/network-observability-console-plugin/pull/195
It adds an `appQuery` that runs in parallel to fill `Total flows time series`.
=> NETOBSERV-409 - Total flows chart

cmd/plugin-backend.go
This set default `lokiTimeout` to 30s as same as our backend server timeout and OCP console proxy one.
https://github.com/openshift/console/blob/f65133a3a85fcbe13ac4227798dae4bfc8ed3cdb/server/proxy.go#L39
=> Increase loki default timeout

Makefile
This PR defines the `SHELL` variable in the Makefile.
This is needed to make `make bridge` work in Ubuntu. Otherwise, it fails with:
```
/bin/sh: 1: source: not found
```
It turns out that by default, `make` is using `/bin/sh` as the shell. ([source](https://www.gnu.org/software/make/manual/html_node/Choosing-the-Shell.html))
While in Ubuntu, `/bin/sh` is a symlink to dash. ([source](https://wiki.ubuntu.com/DashAsBinSh))
The problem is that dash doesn't support the source command. ([source](https://stackoverflow.com/a/13702876/2749989))
=> Define the SHELL variable in the Makefile

web/src/components/__tests__/netflow-traffic.spec.tsx, web/src/components/netflow-traffic.tsx, web/src/utils/overview-panels.ts
This PR remove `overview` feature gate on its tab and adds it on the following panels:
- Network overview
- Top 5 flows distribution
- Packets dropped
- Inbound flows by region
=> NETOBSERV-648 Put unimplemented panels behind feature gates

web/src/components/netflow-record/record-panel.tsx
Force `ClipboardCopy` to `ReadOnly`
=> NETOBSERV-414 change clipboard copy components to read only

web/src/components/netflow-record/record-field.tsx
When `TimeReceived` is missing in a flow, I get the following error when I click on a row in the Flow Table tab.
In this case, `value` is NaN
https://github.com/netobserv/network-observability-console-plugin/blob/db1e8a7abd4609ae85e4afba4570cbf8933b6bcc/web/src/components/netflow-record/record-field.tsx#L174
because the value function of `CollectionTime` multiplies `undefined` by 1000 which happens to be NaN.
https://github.com/netobserv/network-observability-console-plugin/blob/91e6046b571bcdbe796030f173c3d6da1ec988ee/web/src/utils/columns.ts#L687
It turns out that the typeof `NaN` is `number` ([source](https://stackoverflow.com/q/2801601/2749989)) so I had to add a check for NaN values.
=> Make RecordField resilient to NaN values in time fields

web/src/components/query-summary/summary-panel.tsx
forgot to remove a push so it was pushing twice
=> NETOBSERV-701 Cardinality panel: Namespaces listed twice

web/src/components/netflow-topology/netflow-topology.tsx, web/src/components/netflow-traffic.tsx, web/src/components/query-summary/flows-query-summary.tsx, web/src/model/topology.ts
Also remove time range props from NetflowTopology component as it isn't used there anymore
Related to NETOBSERV-602
=> Fix "time range in seconds" calculation in flow query stats

web/src/components/dropdowns/__tests__/truncate-dropdown.spec.tsx, web/src/components/dropdowns/overview-display-dropdown.tsx, web/src/components/dropdowns/topology-display-dropdown.tsx, web/src/components/dropdowns/truncate-dropdown.tsx, web/src/components/metrics/metrics-content.css, web/src/components/metrics/metrics-content.tsx, web/src/components/metrics/metrics-helper.tsx, web/src/components/metrics/metrics-total-content.tsx, web/src/components/metrics/stat-donut.tsx, web/src/components/netflow-overview/__tests__/netflow-overview.spec.tsx, web/src/components/netflow-overview/netflow-overview.tsx, web/src/components/netflow-topology/__tests__/element-panel.spec.tsx, web/src/components/netflow-topology/element-panel.tsx, web/src/components/netflow-traffic.tsx, web/src/model/topology.ts, web/src/utils/local-storage-hook.ts
- Added truncate label option in Overview `Display options`
- Uses existing topology truncate option for side panel graphs
- Adapt text size according to selected truncate length (XS / S are bigger)
- 2 items per row in legend when possible
=> NETOBSERV-688 UI: Overview labels options

web/src/components/netflow-table/__tests__/netflow-table-header.spec.tsx, web/src/components/netflow-table/__tests__/netflow-table.spec.tsx, web/src/components/netflow-table/netflow-table-header.css, web/src/components/netflow-table/netflow-table-header.tsx, web/src/components/netflow-table/netflow-table.tsx, web/src/components/netflow-traffic.tsx
Add table drag & drop capabilities
[Screencast_21_11_2022_14:01:06.webm](https://user-images.githubusercontent.com/91894519/203061870-bfe54dc2-60a3-47cd-8b74-2d78750c4152.webm)
=> NETOBSERV-608 UI: Reorder columns in flow table

web/locales/en/plugin__netobserv-plugin.json, web/src/components/filters/filters-toolbar.tsx, web/src/components/netflow-traffic.css, web/src/components/netflow-traffic.tsx
Added `Time range` and `Refresh interval` labels.
To keep everything consistent & aligned I moved these dropdown at title level. It let more room for filters.
@andrew-ronaldson does that work fine for you ?
=> NETOBSERV-662 UI Consistency: Dropdown labels

web/src/components/modals/__tests__/columns-modal.spec.tsx, web/src/components/modals/columns-modal.tsx, web/src/components/netflow-table/__tests__/netflow-table-header.spec.tsx, web/src/components/netflow-table/__tests__/netflow-table.spec.tsx, web/src/components/netflow-table/netflow-table-header.css, web/src/components/netflow-table/netflow-table-header.tsx, web/src/components/netflow-table/netflow-table.tsx, web/src/components/netflow-traffic.tsx, web/src/utils/columns.ts, web/src/utils/local-storage-hook.ts
Add table resize capabilities
- Custom (min)sizes are stored in local storage
- we only force css min size in `Px` on headers
- the table behavior will not be affected if min size is lower than the default width in `%` 
- Table scroll adapts to new total width
- Reset default columns also reset sizes
[Screencast_22_11_2022_14:41:47.webm](https://user-images.githubusercontent.com/91894519/203328867-84b050fa-860e-4161-a718-259a9d663b78.webm)
Based on https://github.com/netobserv/network-observability-console-plugin/pull/236
=> NETOBSERV-609 UI: Resize a column in flow table

.github/workflows/push_image.yml, .github/workflows/push_image_pr.yml, .github/workflows/release.yml, .golangci.yml, Dockerfile
Backport from `master`: https://github.com/netobserv/network-observability-console-plugin/pull/257
=> Bug NETOBSERV-743: update build image & CI tests to Go 1.18 (release-4.12)

web/package-lock.json
Backport dependabot security fix: https://github.com/netobserv/network-observability-console-plugin/pull/256
Bumps [qs](https://github.com/ljharb/qs) and [express](https://github.com/expressjs/express). These dependencies needed to be updated together.
Updates `qs` from 6.10.2 to 6.11.0
- [Release notes](https://github.com/ljharb/qs/releases)
- [Changelog](https://github.com/ljharb/qs/blob/main/CHANGELOG.md)
- [Commits](https://github.com/ljharb/qs/compare/v6.10.2...v6.11.0)
Updates `express` from 4.17.2 to 4.18.2
- [Release notes](https://github.com/expressjs/express/releases)
- [Changelog](https://github.com/expressjs/express/blob/master/History.md)
- [Commits](https://github.com/expressjs/express/compare/4.17.2...4.18.2)
---
updated-dependencies:
- dependency-name: qs dependency-type: …
=> [4.12 backport] Bump qs and express in /web (#256)

web/src/api/routes.ts, web/src/utils/context.ts
Fixed to remove extra forward slash in URL.
=> NETOBSERV-723 Extra URL request made in Console Plugin

pkg/handler/topology.go, pkg/model/loki.go, pkg/model/loki_test.go, web/src/api/loki.ts, web/src/api/routes.ts, web/src/components/__tests-data__/metrics.ts, web/src/components/netflow-topology/__tests-data__/metrics.ts, web/src/utils/__tests__/metrics.spec.ts, web/src/utils/metrics.ts
Get time from server to parse metrics accordingly.
This avoid a bug when client uses a different time from backend.
=> NETOBSERV-700 UI freeze when client date is after server date

pkg/handler/topology.go, pkg/model/loki.go, pkg/model/loki_test.go, web/src/api/loki.ts, web/src/api/routes.ts, web/src/components/__tests-data__/metrics.ts, web/src/components/netflow-topology/__tests-data__/metrics.ts, web/src/utils/__tests__/metrics.spec.ts, web/src/utils/metrics.ts
Backport of https://github.com/netobserv/network-observability-console-plugin/pull/261
=> NETOBSERV-700 Backport

web/src/components/netflow-traffic.tsx, web/src/utils/router.ts
When `&filters=` is specified without values, the empty filters state is restored.
The default filters are loaded when `filters` url param is missing from both url & local storage.
=> NETOBSERV-741 "Clear all filters" setting is reset back to default when switching panels

web/src/components/modals/columns-modal.tsx, web/src/components/modals/overview-panels-modal.tsx
This PR force popups states to reset on close so a cancel action will sync back to current panels / columns.
=> NETOBSERV-738 Panels & Columns popups keeps their state after cancel

pkg/loki/topology_query.go, pkg/server/server_test.go
This implements `count_over_time` query based on metric type parameter when `count` value is provided.
The result returns the number of flow records during time.
=> NETOBSERV-786 Query: Table Histogram

web/src/components/__tests-data__/config.ts, web/src/components/__tests__/netflow-traffic.spec.tsx, web/src/components/filters/filters-toolbar.tsx, web/src/components/netflow-traffic-parent.tsx, web/src/components/netflow-traffic.tsx
This fix avoid tick being called multiple times at start.
Code changes:
- merged `config` / `forcedFilters` useEffect
- use null when `forcedFilters` are disabled to differenciate with undefined
- `initState` as string array to let developpers better understand what has been done, in which order and allow future states
- log error if tick is wrongly called
=> NETOBSERV-783 multiple page loads with quick filters

web/src/components/filters/filters-toolbar.tsx
Removed quick filters in tabs:
=> NETOBSERV-794 Quick filters doesn't work in tabs

web/src/components/alerts/banner.css, web/src/components/alerts/fetcher.tsx
It seems banner kills page div styling:
I would suggest putting these on `position: absolute`:
=> NETOBSERV-903 banner style fix

Makefile, web/docs/README.md, web/docs/enums/FlowDirection.md, web/docs/interfaces/Fields.md, web/docs/interfaces/Labels.md, web/docs/interfaces/Record.md, web/package-lock.json, web/package.json, web/src/api/ipfix.ts
Hey @jpinsonneau @OlivierCazade  @skrthomas ,
This PR is a first step to automate generating doc for our custom the json format, which now become mandatory to have since it is exposed for kafka export (and it is anyway good to have for people willing to query Loki directly).
I didn't find a satisfying Typescript-API-doc-to-asciidoc tool so what I plan to do is doing this in two steps:
- First, as shown in this PR, generate Typescipt-API-to-markdown here, without much post-edition of the generated files
- Next, open a PR on the operator side that pulls markdown from there, do some post-edition (e.g. merge all in a single file, do some `sed` here and there), and convert to asciidoc. This will allow having our asciidoc consumable for downstream all in one place.
=> NETOBSERV-906 Document json format

config/sample-frontend-config.yaml, pkg/handler/frontend-config.go, web/locales/en/plugin__netobserv-plugin.json, web/src/api/routes.ts, web/src/components/query-summary/summary-panel.css, web/src/components/query-summary/summary-panel.tsx, web/src/model/config.ts
Add sampling configuration in frontend config and show it in the query summary:
=> Added sampling information in frontend config

web/package-lock.json, web/package.json
We have a long-standing report of a vulnerability in `glob-parent` (https://github.com/advisories/GHSA-ww39-953v-wcq6)
This isn't a critical issue in our context of usage - but still, better to get rid of it.
I went into the rabbit hole of the dependency chain but it's this kind of thing:
So, ending up doing an override here :)
=> Bump glob-parent through overrides

web/locales/en/plugin__netobserv-plugin.json, web/src/components/alerts/banner.tsx, web/src/components/alerts/fetcher.tsx, web/src/components/messages/loki-error.tsx
Fix alert id calculation after monitoring operator update and add health dashboard link:
and here (bottom right):
Please note that this PR should be tested with the health [dashboard PR](https://github.com/netobserv/network-observability-operator/pull/299)
=> NETOBSERV-678 Health dashboard link

web/locales/en/plugin__netobserv-plugin.json, web/src/components/metrics/histogram.css, web/src/components/metrics/histogram.tsx, web/src/components/netflow-table/netflow-table-header.tsx, web/src/components/netflow-traffic.css
- border under table headers
- broken lines on right
- increased a bit histogram height
- histogram title (suggestion)
=> Nit CSS updates

pkg/handler/loki.go, pkg/loki/config.go, pkg/server/server_test.go
Reload HOST token from file on every query
=> NETOBSERV-857 After some time, it fails to retrieve flows

web/src/api/alert.ts, web/src/api/routes.ts, web/src/components/__tests__/netflow-traffic.spec.tsx, web/src/components/alerts/fetcher.tsx
The banner will only appear after both query have been done and only non silenced alert will appear.
=> NETOBSERV-908: Added query to get silenced alert and only display non silenced alert

cmd/plugin-backend.go, pkg/handler/export.go, pkg/handler/flows.go, pkg/handler/loki.go, pkg/handler/resources.go, pkg/handler/topology.go, pkg/httpclient/http_client.go, pkg/loki/config.go, pkg/loki/query_test.go, pkg/server/server_flows_test.go
backport of https://github.com/netobserv/network-observability-console-plugin/pull/312
=> [Backport] NETOBSERV-844 Unable to have a working statusUrl in FlowCollector with Loki Operator 5.6

cmd/plugin-backend.go, pkg/handler/export.go, pkg/handler/flows.go, pkg/handler/loki.go, pkg/handler/resources.go, pkg/handler/topology.go, pkg/httpclient/http_client.go, pkg/loki/config.go, pkg/loki/query_test.go, pkg/server/server_flows_test.go
Added status TLS flags for status URL:
- loki-status-skip-tls `Skip TLS checks for loki HTTPS connection`
- loki-status-ca-path `Path to loki status CA certificate`
- loki-status-user-cert-path `Path to loki status user cert for mTLS`
- loki-status-user-key-path `Path to loki status user key for mTLS`
=> NETOBSERV-844 Unable to have a working statusUrl in FlowCollector with Loki Operator 5.6

web/src/components/netflow-tab.tsx, web/src/components/netflow-traffic.css
@andrew-ronaldson found a trailing semicolon in tab view (thanks for that !!)
This PR removes it and fix tab height
=> remove tab trailing semicolon

.github/workflows/pull_request.yml, .github/workflows/push_image.yml, .github/workflows/push_image_pr.yml, .github/workflows/release.yml, .mk/shortcuts.mk, Dockerfile, Makefile, README.md
Implements multi arch builds and add documentation and consistency
```
$ make help
Usage:
make <target>
General
help                  Display this help.
prereqs               Test if prerequisites are met, and installing missing dependencies
vendors               Check go vendors
Develop
start                 Run backend and frontend
start-standalone      Run backend and frontend as standalone
start-standalone-mock  Run backend using mocks and frontend as standalone
bridge                Bridge OCP console
generate-doc          Generate documentation of the flows JSON format
Develop frontend
install-frontend      Run frontend npm install
fmt-frontend          Run frontend i18n and fmt
lint-frontend         Lint frontend code
test-frontend         Test frontend using jest
build-backend …
```
=> NETOBSERV-849 Console plugin multi-arch builds (upstream)

cmd/plugin-backend.go, pkg/kubernetes/auth/check_auth.go, pkg/kubernetes/auth/check_auth_test.go, pkg/kubernetes/client/client.go
Follow-up on #320, which relaxed the permission checks performed when lokiAuth is DISABLED: after discussion, we roll back to a more strict approach; however to mitigate the limitation of TokenReview (it doesn't provide a reliable way to check for cluster admins right), we verify that the user can list namespaces, assuming this is a cluster admin capability.
=> NETOBSERV-972 check if cluster admin via namespaces

.github/workflows/push_image.yml, .github/workflows/push_image_pr.yml, .github/workflows/release.yml, .mk/shortcuts.mk, Makefile, shortlived.Dockerfile
- Can trigger workflow from branch workflow-test
- Make default multi-arch to single amd64
- Remove specific ci targets; make shortlive builds more straightforward
- Disambiguate makefile env vs workflow env
- Remove unused targets
- Remove now unused shortlived dockerfile
- Use docker
=> Update workflow, setup workflow-test

web/locales/en/plugin__netobserv-plugin.json, web/src/components/dropdowns/query-options-dropdown.tsx, web/src/components/netflow-record/record-panel.tsx, web/src/components/netflow-traffic.tsx, web/src/utils/columns.ts
This PR adds direction fields to conversation tracking
Also, it adds JSON fields sorting to be able to easy compare 2 items
Related PRs:
- https://github.com/netobserv/network-observability-operator/pull/313
- https://github.com/netobserv/flowlogs-pipeline/pull/430
=> NETOBSERV-915 add conversation direction

web/src/components/netflow-traffic.tsx
Since `disabledFilters` are loaded from local storage, it can be undefined at first start.
This PR simply ensure the object is initialized and avoid the error.
=> NETOBSERV-997 Cypress test console errors

web/locales/en/plugin__netobserv-plugin.json, web/src/api/ipfix.ts, web/src/components/dropdowns/query-options-dropdown.tsx, web/src/utils/overview-panels.ts
=> Mention 'dropped by the kernel'

web/src/components/__tests-data__/flows.ts, web/src/components/netflow-record/__tests__/record-field.spec.tsx, web/src/utils/columns.ts
=> NETOBSERV-1200: Show "< 1ms" for 0 latency instead of n/a

web/src/components/netflow-topology/netflow-topology.tsx, web/src/components/scope-slider/scope-slider.css, web/src/components/scope-slider/scope-slider.tsx, web/src/components/slider/Slider.tsx, web/src/components/slider/SliderStep.tsx
Borrow slider from patternfly, and adapt for vertical display
=> NETOBSERV-1098: Show scope as slider

web/src/components/filters/filters-chips.tsx, web/src/components/netflow-traffic.tsx, web/src/components/overflow/links-overflow.tsx, web/src/model/__tests__/filters.spec.ts, web/src/model/filters.ts, web/src/model/flow-query.ts, web/src/utils/base-compare.ts
Filters comparison was broken in different ways:
- Same filters with different ordering would be seen as different
- Same filters with different *values* ordering would be seen as different
- Same filters with different display info would be seen as different (when the page is refreshed, the display info on values isn't set)
This commit fixes all of that, and adds tests for each of these scenarios
=> Fix filters comparison

web/src/components/netflow-record/__tests__/record-panel.spec.tsx, web/src/components/netflow-record/record-panel.tsx, web/src/components/netflow-traffic.tsx, web/src/model/filters.ts, web/src/utils/columns.ts
Really simple implementation for pktDrop cause quick filter:
The button is hidden if pktDrop feature is disabled or if flow doesn't have drop cause:
=> NETOBSERV-1216 pktDrop cause filter

web/src/components/netflow-record/record-field.tsx, web/src/utils/pkt-drop.ts
include ovs drops to console plugin
=> NETOBSERV-1135: add ovs subsystem drop causes

web/src/components/netflow-overview/netflow-overview.tsx, web/src/components/netflow-topology/netflow-topology.tsx
- Overview will show "No results found" on the entire page only if every metrics buckets are empty, else it will show per graph results.
- Topology will fallback on dropped metrics if metrics are empty, only for that particular case. Everything then appears red.
=> NETOBSERV-1265 Overview / Topology fully drop metrics doesn't show

web/cypress/e2e/overview/overview.spec.ts, web/cypress/e2e/table/table.spec.ts, web/cypress/e2e/topology/topology.spec.ts, web/cypress/support/commands.ts, web/cypress/support/const.ts, web/src/components/modals/columns-modal.tsx, web/src/components/modals/overview-panels-modal.tsx, web/src/components/netflow-traffic.tsx
Auto refresh seems to retrigger the popups rendering and resets their content.
This PR simply skip `tick` when any popup is open to:
- avoid useless rendering
- keep perfs stable while in popups
=> NETOBSERV-967 skip ticks when popups are open

web/docs/README.md, web/docs/enums/FlowDirection.md, web/docs/enums/InterfaceDirection.md, web/docs/interfaces/Fields.md, web/src/api/ipfix.ts
Regenerating netflows model API doc (that's the first step, another PR will follow on operator repo)
=> Update flow model doc

pkg/loki/flow_query.go, web/src/api/ipfix.ts, web/src/components/netflow-record/record-field.tsx, web/src/components/netflow-record/record-panel.tsx, web/src/components/query-summary/summary-panel.tsx, web/src/utils/columns.ts
Operator PR: https://github.com/netobserv/network-observability-operator/pull/409
=> NETOBSERV-1274 index duplicate (improve query perfs)

web/src/utils/overview-panels.ts
Show DNS & RTT panels by default (when feature enabled)
Backport: https://github.com/netobserv/network-observability-console-plugin/pull/403
n/a
=> NETOBSERV-1313 enable feature gated panels by default

cmd/plugin-backend.go
Following https://github.com/netobserv/network-observability-console-plugin/pull/380 this PR adds new labels to default.
This is usefull for standalone dev.
n/a
=> NETOBSERV-1274 add missing labels to defaults

web/src/utils/columns.ts
Enable RTT column by default 
n/a
=> NETOBSERV-1288 enable rtt column by default

pkg/loki/flow_query.go, web/src/components/metrics/latency-donut.tsx, web/src/components/metrics/single-metrics-total-content.tsx, web/src/components/netflow-overview/netflow-overview.tsx, web/src/components/netflow-traffic.tsx, web/src/components/query-summary/metrics-query-summary.tsx, web/src/utils/columns.ts, web/src/utils/metrics.ts
This PR remove the filter on `NoError` DNS codes on backend side to always return metrics. The filter is done on display side according to the selected options.
It also enable `Show NoError` kebab options by default to avoid having empty graphs at first display.
Finally, `NaN` are skipped in stats generation.
n/a
=> NETOBSERV-1316 & NETOBSERV-1380 - Get dns noError codes to always show graphs

Makefile, config/sample-config.yaml, mocks/loki/flow_records.json, web/src/api/ipfix.ts, web/src/components/netflow-record/record-field.tsx, web/src/components/netflow-traffic.tsx, web/src/utils/columns.ts
- allow mapping on 0
- added functions for duration / latency
- updated sample config
- improved column parsing
https://github.com/netobserv/network-observability-operator/pull/488
Operator PR:
=> NETOBSERV-1400 Feature filters are observed even though they are not enabled

web/src/components/netflow-table/netflow-table-row.tsx, web/src/components/netflow-table/netflow-table.tsx
- table number of columns
- table number of rows
- related column id on each cell
- raw value on each cell
Please let me know if you need extra fields or feel free to update this PR directly :smiley: 
n/a
=> NETOBSERV-1402 Add extra data-test attributes for cypress

pkg/server/common.go, pkg/server/metrics_server.go, pkg/server/server.go, pkg/server/server_test.go
Provide defaults settings for http servers, overridable by callers
n/a
=> NETOBSERV-1102: fine-tune http servers

config/sample-config.yaml, pkg/handler/config.go, web/src/api/ipfix.ts, web/src/components/netflow-record/__tests__/record-field.spec.tsx, web/src/components/netflow-record/record-field.tsx, web/src/components/netflow-record/record-panel.tsx, web/src/components/netflow-table/__tests__/netflow-table-row.spec.tsx, web/src/components/netflow-table/__tests__/netflow-table.spec.tsx, web/src/components/netflow-table/netflow-table-row.tsx, web/src/components/netflow-table/netflow-table.tsx, web/src/components/netflow-traffic.tsx, web/src/utils/columns.ts
Fix missing drops information in table view
FYI there is also https://github.com/netobserv/network-observability-console-plugin/pull/437 opened on `pktDrop` filters
https://github.com/netobserv/network-observability-operator/pull/514
=> NETOBSERV-1432 Missing drops information in table view

web/src/components/query-summary/__tests__/flows-query-summary.spec.tsx, web/src/components/query-summary/__tests__/metrics-query-summary.spec.tsx, web/src/components/query-summary/flows-query-summary.tsx, web/src/components/query-summary/metrics-query-summary.tsx
Renammed `bytes` / `packets` counter ids as follow:
- bytesCount
- bytesPerSecondsCount
- droppedBytesCount
- droppedBytesPerSecondsCount
- packetsCount
- droppedPacketsCount
n/a
=> NETOBSERV-1435 Duplicate Id fields in Query Summary panel when PacketDrop enabled

web/src/api/ipfix.ts
Give more details about what the TCP flags field means
Note, I'm flagging "no-doc" as there will be a doc review later anyway, with re-generated json reference
=> Improve TCP flags doc

web/src/components/netflow-tab.tsx, web/src/components/netflow-traffic-parent.tsx, web/src/components/netflow-traffic.tsx
This PR is a followup of https://github.com/netobserv/network-observability-console-plugin/pull/439 to fix tab crash when loading from direct url / cypress.
n/a
=> NETOBSERV-1429 Netflow tab crash followup

web/locales/en/plugin__netobserv-plugin.json, web/src/components/dropdowns/query-options-dropdown.tsx
Quick fix on how to enable packet drop feature.
n/a
=> Packet drop message update

web/package-lock.json, web/package.json, web/src/index.tsx
As mobx is also used by the console itself, it must be configured as isolated to prevent conflicting versions.
n/a
=> NETOBSERV-1450: use isolated states for mobx

web/src/components/filters/autocomplete-filter.css, web/src/components/filters/autocomplete-filter.tsx, web/src/utils/filter-definitions.ts, web/src/utils/filter-options.ts
Add a button next to `autocompletes` to open / close suggestions.
Also added a scroller when options are more than 8.
[Screencast from 2024-01-23 11-17-14.webm](https://github.com/netobserv/network-observability-console-plugin/assets/91894519/9351f3e2-e79a-4be1-9132-cf1070281c4e)
n/a
=> NETOBSERV-1355 autocomplete menu button

web/locales/en/plugin__netobserv-plugin.json, web/src/components/filters/filters-toolbar.css, web/src/components/modals/columns-modal.css, web/src/components/modals/columns-modal.tsx, web/src/components/modals/export-modal.tsx, web/src/components/modals/overview-panels-modal.css, web/src/components/modals/overview-panels-modal.tsx
Add view filters to quickly pick panels / columns:
Panel ids are updated in https://github.com/netobserv/network-observability-console-plugin/pull/412
=> NETOBSERV-267 Panels & columns popup filters

web/src/components/dropdowns/topology-display-dropdown.css, web/src/components/metrics/histogram.tsx, web/src/components/metrics/metrics-content.css, web/src/components/metrics/metrics-donut.tsx, web/src/components/metrics/metrics-graph-total.tsx, web/src/components/metrics/metrics-graph.tsx, web/src/components/modals/export-modal.tsx, web/src/components/netflow-overview/netflow-overview.tsx, web/src/components/netflow-topology/element-panel-metrics.tsx, web/src/components/netflow-topology/element-panel.tsx, web/src/components/netflow-traffic.css, web/src/components/netflow-traffic.tsx, web/src/utils/export.ts
I found various issues while reviewing the entire plugin CSS. This PR fixes:
- CSS light & dark theme for OCP 4.15+
- Overview export while focus mode
[Screencast from 2024-01-29 17-21-14.webm](https://github.com/netobserv/network-observability-console-plugin/assets/91894519/81287518-1b1a-4f64-9f0b-c7fdb17f7a30)
- Table export columns selection
n/a
=> NETOBSERV-1416 polishing & fixes

web/src/components/netflow-topology/netflow-topology.tsx, web/src/components/scope-slider/scope-slider.css, web/src/components/scope-slider/scope-slider.tsx
This is a temporary fix to manage scope slider positionning. 
Currently, the slider can cover other components and mess up with zoom buttons.
In this patch, the scope slider only display when possible and adapt it size and position.
I would suggest to backport this to 1.5 if that works for everyone.
n/a
=> NETOBSERV-1475 zoom-in button on topology view is unclickable in collapse mode

web/src/api/ipfix.ts, web/src/components/netflow-record/record-panel.tsx
Flow query is buggy and returns all fields as labels when using some filters.
Since we moved to dynamic config, we check both labels and fields and pick the first match.
This PR invert check order: fields before labels, to keep correct field types.
A followup for 1.6 is coming with proper field type parsing:
https://issues.redhat.com/browse/NETOBSERV-1503
n/a
=> NETOBSERV-1496 netflow page table view crashes when using Destination IP as filter

config/sample-config.yaml, pkg/handler/config.go, web/src/api/ipfix.ts, web/src/api/routes.ts, web/src/components/__tests-data__/columns.ts, web/src/components/__tests-data__/config.ts, web/src/components/modals/columns-modal.tsx, web/src/components/modals/export-modal.tsx, web/src/components/netflow-record/record-panel.tsx, web/src/components/netflow-traffic.tsx, web/src/model/config.ts, web/src/utils/columns.ts, web/src/utils/fields.ts
Followup on https://github.com/netobserv/network-observability-operator/pull/550:
I decided to keep `loki.labels` instead of reusing fields `lokiLabel` since these are generated only for documentation purpose for now.
n/a
=> NETOBSERV-1503 Console plugin fields config

mocks/updateMocks.sh, pkg/loki/filter.go, pkg/loki/flow_query.go, pkg/server/server_flows_test.go, pkg/server/server_test.go
Use `Duplicate != true` to deduplicate since we don't append false value anymore
Allows https://github.com/netobserv/netobserv-ebpf-agent/pull/276 removing `Duplicate` field when not necessary
=> NETOBSERV-1466 rely on duplicate different than 'true'

web/src/components/netflow-traffic.tsx, web/src/utils/__tests__/flows.spec.ts, web/src/utils/columns.ts, web/src/utils/flows.ts
This PR currently just shows the cross-nodes duplicates.
Following the reproduce steps described in [NETOBSERV-1551](https://issues.redhat.com//browse/NETOBSERV-1551), I'm now seeing both interfaces:
But they are displayed as distinct flows. So it raises the question: should we reintroduce the "Show duplicates" checkbox, since there are still the cross-nodes duplicates even in merge mode? Or should we merge them post-query without asking? If we do so, what to put in Node Direction? "both" ?
n/a
=> NETOBSERV-1551: show cross-nodes duplicates in merge mode

.github/workflows/pull_request.yml, .github/workflows/push_image.yml, Dockerfile, Dockerfile.cypress, Makefile, web/package-lock.json, web/package.json
Upgrade to node18, bump some libs
n/a
=> NETOBSERV-1575: Upgrade to node18, bump some libs

web/src/model/flow-query.ts
Steps to reproduce:
- Show latest bytes
- Switch to DNS
Metric function `must` switch to `average`.
n/a
=> NETOBSERV-1596 fix latest not resetting on DNS / RTT metrics

config/sample-config.yaml, web/docs/interfaces/Fields.md, web/locales/en/plugin__netobserv-plugin.json, web/src/api/ipfix.ts, web/src/components/__tests-data__/columns.ts, web/src/components/__tests-data__/filters.ts, web/src/utils/overview-panels.ts
=> Remove references to *handshake* RTT (it's sRTT)

pkg/loki/flow_query.go, pkg/model/filters/logql.go
Allow `not` for ip filters
https://grafana.com/docs/loki/latest/query/ip/
n/a
=> NETOBSERV-1630 allow not for ip filters

.github/workflows/pull_request.yml, .github/workflows/push_image.yml, .github/workflows/push_image_pr.yml, .github/workflows/release.yml, .golangci.yml, Dockerfile, Dockerfile.ci, Dockerfile.cypress, web/src/components/messages/error.tsx
=> NETOBSERV-1707: move to go 1.22

pkg/handler/topology.go
Note, there's just nothing to do on the console plugin side, this is all managed in https://github.com/netobserv/network-observability-operator/pull/676
=> NETOBSERV-1649: remove obsolete comment

web/src/components/netflow-topology/2d/topology-content.tsx, web/src/components/netflow-topology/netflow-topology.tsx, web/src/components/netflow-traffic.tsx, web/src/model/topology.ts
Fixes also [NETOBSERV-1721](https://issues.redhat.com//browse/NETOBSERV-1721) and [NETOBSERV-1722](https://issues.redhat.com//browse/NETOBSERV-1722)
- new func getStepIntoNext that provides the next scope for 'stepInto' and cares about the allowed scopes
- fix call to toggleDirElementFilter on stepInto (it was *removing* the filter instead of adding it), and prevent adding duplicate filters
- Do not link groups invalidation to scope via useEffect, as it results in doing 2 queries (first with the invalid group, then without). Make them more strictly tied instead.
Also, this PR changes the stepInto workflow when coming from nodes, it jumps directly to pods. Two reasons for that:
- this seems more logical to see pods rather than namespaces when "stepping into a node". Namespaces and Nodes …
=> NETOBSERV-1720: fix issues with topology scopes

pkg/model/fields/fields.go, web/src/components/drawer/record/record-field.tsx, web/src/utils/columns.ts, web/src/utils/filter-definitions.ts, web/src/utils/filter-options.ts, web/src/utils/tcp_flags.ts
Allow filtering based on TCP flags
https://github.com/netobserv/netobserv-ebpf-agent/pull/367
https://github.com/netobserv/network-observability-operator/pull/710
=> NETOBSERV-1756 Allow filtering based on TCPFlags values

web/src/components/drawer/record/record-field.css
Force tooltip style to display properly on every OCP version
n/a
=> NETOBSERV-1768 force tooltip style

web/locales/en/plugin__netobserv-plugin.json, web/src/components/toolbar/filters-toolbar.tsx, web/src/components/toolbar/filters/autocomplete-filter.tsx, web/src/components/toolbar/filters/text-filter.tsx, web/src/model/filters.ts, web/src/utils/filter-definitions.ts
Allow filtering on `n/a` by searching on strict value `""` in the text input.
n/a
=> NETOBSERV-1816 allow n/a filter

web/src/components/dropdowns/__tests__/metric-type-dropdown.spec.tsx, web/src/components/dropdowns/metric-type-dropdown.tsx, web/src/components/dropdowns/topology-display-dropdown.tsx, web/src/components/dropdowns/topology-display-options.tsx, web/src/components/netflow-traffic.tsx, web/src/components/tabs/netflow-overview/panel-kebab.tsx, web/src/components/toolbar/view-options-toolbar.tsx, web/src/model/netflow-traffic.ts, web/src/utils/router.ts
Invalidate local storage values when necessary:
- record type
- datasource
- packet loss
- metric scope / group
- metric type / function
Columns / panels should not be impacted as already working properly.
n/a
=> NETOBSERV-1783 invalidate local storage values

web/src/utils/ids.ts
Don't append ip to topology ids when not needed.
=> NETOBSERV-1818: Topology split pod when using two IPs

pkg/handler/loki.go
We're seeing a lot of errors with "no message found". This is because with Loki operator 6, the json of the error has changed. We need now to look at the "error" field.
Also add more debug logs
=> Fix error logs/message for loki-op 6

web/src/components/netflow-traffic.tsx
Postpone tick if drawer not rendered
This bug was introduced by https://github.com/netobserv/network-observability-console-plugin/pull/558
n/a
=> NETOBSERV-1871 First request to get flow data waits indefinitely on workloads network-traffic page

pkg/handler/loki.go
Backport of https://github.com/netobserv/network-observability-console-plugin/pull/617
We're seeing a lot of errors with "no message found". This is because with Loki operator 6, the json of the error has changed. We need now to look at the "error" field.
Also add more debug logs
=> Fix error logs/message for loki-op 6 [1.7 backport]

.github/workflows/push_image.yml, .github/workflows/push_image_pr.yml, .github/workflows/release.yml, Dockerfile, Makefile
It will save time during rebuilds for the developers, since the current time isn't passed to the go build anymore, which was previously forcing to refresh the docker layers
=> Distinguish "clean builds" and dev builds

config/sample-config.yaml, pkg/server/routes.go, web/src/api/routes.ts, web/src/components/toolbar/filters-toolbar.tsx
- Fix `resources` endpoint params not working. The routes:
```
"/resources/namespace/{namespace}/kind/{kind}/names"
"/resources/kind/{kind}/names"
```
are now moved to a single one:
```
"/resources/names"
```
The namespace and kind are now parameters instead of url parts.
- Improve filter toolbar to not crash when namespace filter is not available (mainly for dev purposes)
https://github.com/netobserv/network-observability-operator/pull/820 for field descriptions update
=> NETOBSERV-1885: fix resources/names endpoint

Dockerfile
same as https://github.com/netobserv/network-observability-operator/pull/769 , with some extra cleaning
=> Dockerfile cleanup: remove unused args

web/src/utils/flows.ts
show flows with network events set for duplicated flows
n/a
=> NETOBSERV-1951: show flows with networkevents 1st for duplicate flows

web/src/components/drawer/record/record-field.tsx
I am often seeing JS errors in the console, I think happens when I'm switching between browser tabs and DOM not fully rendered yet, but not sure ...
The error is like:
```
Uncaught TypeError: e.currentTarget.children[0] is undefined
D record-field.tsx:25
onMouseOver record-field.tsx:117
React 11
unstable_runWithPriority scheduler.production.min.js:18
React 9
<anonymous> app.jsx:356
Webpack 6
record-field.tsx:25:16
D record-field.tsx:25
onMouseOver record-field.tsx:117
React 11
unstable_runWithPriority scheduler.production.min.js:18
React 4
forEach self-hosted:4297
React 5
<anonyme> app.jsx:356
Webpack 6
```
So this should fix it
=> Fix Uncaught TypeError: e.currentTarget.children[0] is undefined

.tekton/pipeline-ref.yaml, Dockerfile.downstream
Fix version in konflux build
n/a
=> Fix version in konflux build

.golangci.yml, pkg/loki/flow_query.go, pkg/model/filters/logql.go, pkg/model/filters/logql_test.go, pkg/server/server_flows_test.go, web/src/model/__tests__/filters.spec.ts
NOT filters with multiple values should generate AND queries, not OR E.g. IP=10.0.0.1,10.0.0.2 generates IP=10.0.0.1 OR IP=10.0.0.2, which is correct
But, IP!=10.0.0.1,10.0.0.2 should not generate IP!=10.0.0.1 OR IP!=10.0.0.2 (which would be always true) but IP!=10.0.0.1 AND IP!=10.0.0.2 instead
Reasoning with CIDRs is the same:
IP!=10.0.0.0/8,172.0.0.0/8 translates into IP NOT IN 10.0.0.0/8 AND IP NOT IN 172.0.0.0/8
Screens:
Filtering out traffic to pods
Filtering our traffic to services and pods
n/a
=> NETOBSERV-1990: fix NOT filters with multiple values

web/src/model/topology.ts, web/src/utils/metrics.ts
Followup on https://github.com/netobserv/network-observability-console-plugin/pull/634 to fix topology issues
n/a
=> NETOBSERV-1927 fix topology issues

pkg/model/fields/fields.go
Add xlat field's filters to hardcoded numberic and ip lists
n/a
=> NETOBSERV-2056: Add xlat filters to hardcode fields list

config/sample-config.yaml, mocks/loki/flow_metrics_dropped_udn.json, mocks/loki/flow_metrics_udn.json, mocks/loki/flow_records.json, mocks/loki/flow_records_has_dropped.json, mocks/loki/flow_records_sent.json, pkg/handler/lokiclientmock/loki_client_mock.go, pkg/handler/resources.go, pkg/model/fields/fields.go, pkg/server/routes.go, scripts/update-config.sh, web/console-extensions.json, web/locales/en/plugin__netobserv-plugin.json, web/src/api/ipfix.ts, web/src/api/loki.ts, web/src/api/routes.ts, web/src/app.tsx, web/src/components/drawer/element/element-panel-content.tsx, web/src/components/drawer/record/record-field.tsx, web/src/utils/autocomplete-cache.ts, web/src/utils/columns.ts, web/src/utils/filter-definitions.ts, web/src/utils/filter-options.ts
- extra tabs for CUDN and UDN resources
- UDN field showing link to resources
- autocomplete
- updated mocks
https://github.com/netobserv/network-observability-operator/pull/909 to get the config deployed
=> NETOBSERV-1902 Additionnal graphs + tab + autocomplete for UDN

pkg/handler/response.go, pkg/handler/topology.go, web/locales/en/plugin__netobserv-plugin.json, web/src/components/drawer/netflow-traffic-drawer.tsx, web/src/components/messages/error.tsx, web/src/components/netflow-traffic.css, web/src/components/netflow-traffic.tsx, web/src/components/tabs/netflow-topology/netflow-topology.tsx, web/src/components/toolbar/filters/chips-popover.tsx, web/src/model/netflow-traffic.ts, web/src/utils/errors.ts
=> NETOBSERV-1977 automatically disable filters when not available in prometheus

config/sample-config.yaml, mocks/loki/flow_records.json, pkg/handler/lokiclientmock/loki_client_mock.go, web/cypress/e2e/table/fields.spec.ts, web/src/components/__tests-data__/flows.ts
Additionnal cypress tests for featured columns
n/a
=> NETOBSERV-2004 Additionnal UI e2e tests for features columns

web/src/components/drawer/record/record-field.css, web/src/components/drawer/record/record-field.tsx
Improve table display to avoid inconsistent row heights.
n/a
=> NETOBSERV-2049: Console table rows height are inconsistent

web/locales/en/plugin__netobserv-plugin.json, web/src/components/drawer/record/record-panel.css, web/src/components/drawer/record/record-panel.tsx
=> NETOBSERV-1992: explain partial flows

web/locales/en/plugin__netobserv-plugin.json, web/src/components/drawer/record/record-panel.css, web/src/components/drawer/record/record-panel.tsx
Ref: https://github.com/netobserv/network-observability-console-plugin/pull/683
=> NETOBSERV-1992: explain partial flows [backport 1.8]

.tekton/pipeline-ref.yaml, Dockerfile.downstream, Dockerfile.front.downstream
Similar to what was done for upstream in https://github.com/netobserv/network-observability-console-plugin/pull/707
n/a
=> Konflux building frontend only once

Dockerfile, Dockerfile.front, Makefile
The goal is to avoid redundant frontend builds for each architecture, since the frontend artifacts are just plain text files / noarch.
For now it's only for upstream builds, but the goal would be to have the same with konflux
=> Avoid redundant frontend builds

.tekton/network-observability-console-plugin-1-8-pull-request.yaml, .tekton/network-observability-console-plugin-1-8-push.yaml, .tekton/pipeline-ref.yaml, Dockerfile.downstream, Dockerfile.front.downstream
Building frontend only once to avoid oom errors on arm builds.
n/a
=> backport: Building frontend only once (#718)

Dockerfile.downstream
Backport of https://github.com/netobserv/network-observability-console-plugin/pull/725
=> FIPS compliance [backport 1.8]

Dockerfile.downstream
=> Adding ignore-script flag to npm during konflux builds

web/src/components/netflow-traffic.tsx, web/src/model/config.ts, web/src/model/filters.ts
Some of the features filtering is still hardcoded such as for filters.
I would suggest to merge this for now as a quick win and investigate about a more generic solution in parallel.
n/a
=> NETOBSERV-2104 Filters in UI are visible despite features are disabled

web/console-extensions.json
Console is now showing Observe menu without Prom & Monitoring flags
We must remove the Observe menu entry from our plugin since it now duplicates in the console.
This is a good candidate for 1.8.1 release for users on 4.14 and below
Ensure https://github.com/openshift/console/pull/14697 is properly backported before merging this !
=> NETOBSERV-2139 remove observe menu entry

pkg/server/routes.go, web/moduleMapper/dummy.tsx, web/package-lock.json, web/package.json, web/setup-tests.tsx, web/src/api/routes.ts, web/src/app.tsx, web/src/components/__tests__/netflow-tab.spec.tsx, web/src/components/__tests__/netflow-traffic.spec.tsx, web/src/components/netflow-traffic-dev-tab.tsx, web/src/components/netflow-traffic-parent.tsx, web/src/components/netflow-traffic-tab.tsx, web/src/components/netflow-traffic.css, web/src/components/netflow-traffic.tsx, web/src/utils/context.ts, web/webpack.config.ts, web/webpack.standalone.ts
Add namespace bar on top of the page when the user doesn't have the admin role.
The page will act as same as in the developer perspective in that case.
For admins, the selector is not showing.
based on https://github.com/netobserv/network-observability-console-plugin/pull/658
=> NETOBSERV-2098: Unified-perspectives

pkg/handler/k8s.go, pkg/kubernetes/auth/check_auth.go, pkg/kubernetes/resources/resources.go, pkg/server/routes.go, vendor/k8s.io/client-go/dynamic/interface.go, vendor/k8s.io/client-go/dynamic/scheme.go, vendor/k8s.io/client-go/dynamic/simple.go, vendor/modules.txt, web/locales/en/plugin__netobserv-plugin.json, web/src/api/routes.ts, web/src/components/drawer/element/element-panel-content.tsx, web/src/components/drawer/element/element-panel.tsx, web/src/components/drawer/netflow-traffic-drawer.tsx, web/src/components/dropdowns/topology-display-options.tsx, web/src/components/netflow-traffic.tsx, web/src/components/tabs/netflow-topology/2d/styles/styleNode.tsx, web/src/components/tabs/netflow-topology/2d/topology-content.tsx, web/src/components/tabs/netflow-topology/__tests__/netflow-topology.spec.tsx, web/src/components/tabs/netflow-topology/netflow-topology.tsx, web/src/model/netflow-traffic.ts, web/src/model/topology.ts
=> NETOBSERV-1905 Query UDNs without flows

web/src/components/netflow-traffic.tsx, web/src/model/config.ts, web/src/model/filters.ts
[NETOBSERV-2233](https://issues.redhat.com//browse/NETOBSERV-2233) Make IPSec filters visible if feature is enabled
n/a
=> NETOBSERV-2233 Make IPSec filters visible if feature is enabled

web/src/components/tabs/netflow-table/netflow-table.tsx, web/src/utils/columns.ts
Array columns were not correctly handled
n/a
=> NETOBSERV-2239: fix sorting by packets/bytes

web/src/components/tabs/netflow-topology/2d/topology-content.tsx, web/src/model/topology.ts
Fix empty UDN's filtering not working as expected
n/a
=> NETOBSERV-2244: show topology when expectedNodes is set
